name: trust_aid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  http: ^1.2.0
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.2.0
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  rxdart: ^0.27.7
  pin_code_fields: ^8.0.1
  injectable: ^2.3.0
  go_router: ^13.2.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2 
  mockito: ^5.0.15
  mocktail: ^0.2.0
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
     - asset/
     - asset/images/
     - asset/ringtunes/iphone.mp3
     - asset/ringtunes/android.wav

  fonts:
    - family: SFPro
      fonts:
        - asset: asset/fonts/sfpro_regular.otf
        - asset: asset/fonts/sfpro_bold.otf
          weight: 700
        - asset: asset/fonts/sfpro_regular.otf
        - asset: asset/fonts/sfpro_medium.otf
          weight: 500